# OtterTune Driver Configuration for Deployment

# ====================================================================
#  SERVER OPTIONS
# ====================================================================
# This section is required for connecting to the ottertune compute server

# URL of the OtterTune server that the driver communicates with
server_url: 'https://api.ottertune.com'

# ====================================================================
#  METRICS OPTIONS
# ====================================================================
# This section is required for determining what metrics to collect

metric_source: ["cloudwatch"]

# ====================================================================
#  DRIVER OPTIONS
# ====================================================================
# Setup pertinent to ottertune agent driver behavior

monitor_interval: 60
num_table_to_collect_stats: 1000
