# OtterTune Driver Configuration for Deployment

# ====================================================================
#  SERVER OPTIONS
# ====================================================================
# This section is required for connecting to the ottertune compute server

# URL of the OtterTune server that the driver communicates with
server_url: "https://api.ottertune.com"

# ====================================================================
#  METRICS OPTIONS
# ====================================================================
# This section is required for determining what metrics to collect

metric_source: ["cloudwatch"]

# ====================================================================
#  DRIVER OPTIONS
# ====================================================================
# Setup pertinent to ottertune agent driver behavior

monitor_interval: 60
table_level_monitor_interval: 3600
num_table_to_collect_stats: 1000
num_index_to_collect_stats: 10000
long_running_query_monitor_interval: 240
query_monitor_interval: 3600
num_query_to_collect: 10000
schema_monitor_interval: 3600
